/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PackageGTN;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class FormGTN extends javax.swing.JFrame {

    private final String sep = " ";
    private int[] stats = new int[5];//attempts, currentstreak, beststreak, correct, wrong;
    private int solution = 0;
    
    public static int GenerateNumber(){
        Random random = new Random();
        int number = 1 + random.nextInt(100);
        
        return number;
    }
    /**
     * Creates new form FormGTN
     */
    public FormGTN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBestStreak = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorrect = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtWrong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtWins = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAttemps = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        btnPlay = new javax.swing.JButton();
        btnGuess = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCarica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("GUESS THE NUMBER");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("Best Streak:");

        txtBestStreak.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setText("Correct:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtCorrect.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("Wrong:");

        txtWrong.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("% Win:");

        txtWins.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Guess the Number (range 1-100) in 5 attemps");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("Enter your number:");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setText("Attemps remaining:");

        txtAttemps.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setText("Answer:");

        txtAnswer.setEditable(false);

        btnPlay.setBackground(new java.awt.Color(255, 0, 0));
        btnPlay.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnPlay.setText("PLAY");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnGuess.setBackground(new java.awt.Color(255, 0, 0));
        btnGuess.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnGuess.setText("GUESS");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 0, 0));
        btnReset.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCarica.setBackground(new java.awt.Color(255, 0, 0));
        btnCarica.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnCarica.setText("LOAD");
        btnCarica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBestStreak, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtWins, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                        .addComponent(txtWrong, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(156, 156, 156)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCorrect)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(17, 17, 17))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(64, 64, 64)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7)
                                                .addComponent(btnCarica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(jLabel8))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(txtAttemps, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(19, 19, 19))))
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBestStreak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAttemps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtWrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarica, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        try{
            if(stats[0]>0){
                JOptionPane.showMessageDialog(null, "You must finish your attempts first!");
            }else{
                //it generates a random number
                solution = GenerateNumber();
                txtAnswer.setText("");
                txtNumber.setText("");
                //replace the number of attempts
                stats[0] = 5;
                txtAttemps.setText(Integer.toString(stats[0]));
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+ e);
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        int guess;
                
        try{
            if(txtNumber.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Enter a number!");
            }else if (Integer.parseInt(txtNumber.getText())>100 || Integer.parseInt(txtNumber.getText())<1){
                JOptionPane.showMessageDialog(null, "Enter a number from 1 to 100!");
            }else if(stats[0] == 0){
                JOptionPane.showMessageDialog(null, "Start a new game first!");
            }else{
                guess = Integer.parseInt(txtNumber.getText());
                
                if(solution==0){//it means the solution hasn't been generated yet.
                    JOptionPane.showMessageDialog(null, "You didn't start the game, so we have done it for you :D\nClick guess again!");
                    btnPlay.doClick(100);
                }else{
                    if (guess == solution){
                            JOptionPane.showMessageDialog(null, "You have won!");
                            stats[1]++;//currentStreak
                            stats[3]++;//correct
                            stats[0] = 0;//reset attempts
                            
                            float total = stats[3]+stats[4];
                            float wins = (stats[3]/total)*100;
                            txtWins.setText((int)wins+"%");
                            txtCorrect.setText(Integer.toString(stats[3]));
                            txtAnswer.setText(Integer.toString(solution));
                            
                            
                        }else if(guess > solution){
                            stats[0]--;
                            txtAttemps.setText(Integer.toString(stats[0]));
                            JOptionPane.showMessageDialog(null, "The solution is lower!");
                            
                            if(stats[0]==0){
                                JOptionPane.showMessageDialog(null, "You have finished your attemps!");
                                txtAnswer.setText(Integer.toString(solution));//show the solution
                                if(stats[1]>stats[2]){
                                    stats[2]=stats[1];//check if the currentStreak is higher than the bestStreak
                                }
                                stats[1]=0;//reset the currentStreak
                                stats[4]++;//wrong
                                
                                txtBestStreak.setText(Integer.toString(stats[2]));
                                txtWrong.setText(Integer.toString(stats[4]));
                                float total = stats[3]+stats[4];
                                float wins = (stats[3]/total)*100;
                                txtWins.setText((int)wins+"%");
                            }
                        }else{
                            stats[0]--;
                            txtAttemps.setText(Integer.toString(stats[0]));
                            JOptionPane.showMessageDialog(null, "The solution is higher!");
                            
                            
                            if(stats[0]==0){
                                JOptionPane.showMessageDialog(null, "You have finished your attemps!");
                                txtAnswer.setText(Integer.toString(solution));//show the solution
                                if(stats[1]>stats[2]){
                                    stats[2]=stats[1];//check if the currentStreak is higher than the bestStreak
                                }
                                stats[1]=0;//reset the currentStreak
                                stats[4]++;//wrong
                                
                                txtBestStreak.setText(Integer.toString(stats[2]));
                                txtWrong.setText(Integer.toString(stats[4]));
                                float total = stats[3]+stats[4];
                                float wins = (stats[3]/total)*100;
                                txtWins.setText((int)wins+"%");
                            }
                        }
                    }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+ e);
        }
    }//GEN-LAST:event_btnGuessActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtBestStreak.setText(Integer.toString(stats[2]));
        txtCorrect.setText(Integer.toString(stats[3]));
        txtWrong.setText(Integer.toString(stats[4]));
        txtWins.setText("0%");
        txtAttemps.setText(Integer.toString(stats[0]));
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try{
            FileWriter fw = new FileWriter("output.txt");
            PrintWriter pw = new PrintWriter(fw);
            
            pw.print(stats[1]+sep+stats[2]+sep+stats[3]+sep+stats[4]);
            fw.close();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Errore: "+ e);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try{
            if(stats[0]>0){
                JOptionPane.showMessageDialog(null, "You must finish your attempts first!");
            }else{
                stats[1]=0;
                stats[2]=0;
                stats[3]=0;
                stats[4]=0;
                txtAttemps.setText(Integer.toString(stats[0]));
                txtBestStreak.setText(Integer.toString(stats[2]));
                txtCorrect.setText(Integer.toString(stats[3]));
                txtWrong.setText(Integer.toString(stats[4]));
                txtWins.setText("0%");
                txtAnswer.setText("");
                txtNumber.setText("");
            }
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Errore: "+ e);
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaActionPerformed
        String[] vs = new String[4];
        
        try{
            if(stats[0]>0){
                JOptionPane.showMessageDialog(null, "You must finish your attempts first!");
            }else{
                FileReader fr = new FileReader("output.txt");
                BufferedReader br = new BufferedReader(fr);

                String line = br.readLine();
                vs = line.split(sep);

                stats[1]=Integer.parseInt(vs[0]);
                stats[2]=Integer.parseInt(vs[1]);
                stats[3]=Integer.parseInt(vs[2]);
                stats[4]=Integer.parseInt(vs[3]);
                
                txtAttemps.setText(Integer.toString(stats[0]));
                txtBestStreak.setText(Integer.toString(stats[2]));
                txtCorrect.setText(Integer.toString(stats[3]));
                txtWrong.setText(Integer.toString(stats[4]));
                float total = stats[3]+stats[4];
                float wins = (stats[3]/total)*100;
                txtWins.setText((int)wins+"%");
                txtAnswer.setText("");
                txtNumber.setText("");
                
                
            }  
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Errore: "+ e);
        }
    }//GEN-LAST:event_btnCaricaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGTN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGTN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGTN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGTN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGTN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarica;
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtAttemps;
    private javax.swing.JTextField txtBestStreak;
    private javax.swing.JTextField txtCorrect;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtWins;
    private javax.swing.JTextField txtWrong;
    // End of variables declaration//GEN-END:variables
}
